name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Send Discord notification on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "✅ Tests passed for '${{ github.repository }}' on commit '${{ github.sha }}'"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
